### ISSUE TITLE
Update versioning

### ISSUE THREAD

**Issue by IzzySoft** [danielshorten/k9t9#14]
While the tags show multiple releases with the latest one being named `0.11.0`, the APK always identifies as

    package: name='com.shortendesign.k9keyboard' versionCode='1' versionName='1.0' compileSdkVersion='31' compileSdkVersionCodename='12'

* `versionCode` should be increased with each release; it's what Android uses internally to tell versions apart and signal updates
* `versionName` is what is shown to the user (and should be in sync with your tag names), so it's important for issues reported (to know what version is affected)

Could you please adjust that (for future releases)? Thanks in advance!

**Comment by danielshorten** [comment]
Thanks.  I'm very new to Android development so appreciate these pointers.

**Comment by IzzySoft** [comment]
Thanks a lot! I've just pulled the latest update manually (my updater refused as 0.12.0 is smaller than 1.0 – but that was to be expected; from now on it will work correctly as versioning is fixed).
