### ISSUE TITLE
Letter entry mode

### ISSUE THREAD

**Issue by danielshorten** [danielshorten/k9t9#15]
Add a letter-by-letter text entry mode, where:
- keys can be pressed repeatedly to cycle through the characters assigned to them.
- after a pause of around a second the character will be committed, and pressing another key will begin entry for the next letter.

**Comment by paweloo85** [comment]
Daniel, that would be excellent addition. I'm trying to set up Qin F22 Pro for elder person. Everything works great, but without letter entry mode it is impossible to use for non-english user :)
