### ISSUE TITLE
APK not installing properly

### ISSUE THREAD

**Issue by Bumbledries** [danielshorten/k9t9#18]
This might be me, but I tried to install the keyboard on my phone (0.11.0) by APK with both directly downloading it on my phone and with ADB. The installing works, but when I try to pull the property file to change the keymapping it says there is settings file available. Same goes when I try to retrieve the file in my phone settings. And indeed, on the default location no file (or folder) has been created. 

I think it has to do with the app not installing correctly, but it says it does and I have no idea how to do it otherwise.

**Comment by danielshorten** [comment]
Hi!

You said you tried to pull the property file to change the key mapping.  You need to push a properties file from your machine to the device.
