### ISSUE TITLE
Fix cross-resolution scaling of input mode indicator

### ISSUE THREAD

**Issue by mbg71** [danielshorten/k9t9#19]
This is by far the best T9 input for the F21 Pro I've tried.

One wrinkle is that the input mode indicator ("12" etc) is so tiny as to be unreadable. Please see the attached zoomed screenshot which has the icon circled in yellow.

![Screenshot_20221104-182611](https://user-images.githubusercontent.com/537290/200081989-a4bd3aea-f51e-48c7-89e0-1c7203f0b01f.png)

Phone is Qin F21 Pro global version, which came from Alibaba with Google Play preinstalled.

alps-mp-r0.mp1-V7.13 build number 1.1.5

**Comment by danielshorten** [comment]
Thanks for the report!
I've noticed this even on my little ZTE Cymbal 2 flip phone.  I have an idea about how this might be improved.
