### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Alliyanya** [danielshorten/k9t9#26]
I just downloaded it on my F-22 Pro, however I'm stuck at the beginning of read me, I was wondering if you could explain to me in more detail how to begin the installation and what ADB means? That would be quite helpful thank you so much I hope to hear back from you!

**Comment by danielshorten** [comment]
Hi there!

You start reading up on ADB here: https://developer.android.com/studio/command-line/adb

As I mention in the [README](https://github.com/danielshorten/k9t9#philosophy--limitations), this is an early version of an app targeted at fairly basic and locked-down Android feature phones, so a little technical knowledge is required to get it set up and configured.  Unfortunately I can't provide support for installing and using ADB and the Android SDK, but there's lots of info and support out there!

**Comment by Alliyanya** [comment]
You are so kind for helping me ! Thank you for this information and reply
!!!
